apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: social-network-neo4j-core-0
  ports:
  - protocol: TCP
    name: internet
    port: 7474
    targetPort: 7474
  - protocol: TCP
    port: 7687
    name: bolt
    targetPort: 7687
